import Head from "next/head";
import Image from "next/image";
import React from "react";
import { OurservicesCardMapping } from "../Components/AllCards/ourServicescards";
import Hero from "../Components/hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>DHT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <section className="mt-[px] bg-white" id="ourservices">
          <OurservicesCardMapping />
        </section>
      </main>
    </>
  );
}
4;
