import Head from "next/head";
import Image from "next/image";
import Contact from "@/Components/contactUs";
import { ContactM } from "@/Components/contactUs";

export default function Home() {
  return (
    <>
      <Head>
        <title>DHT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Contact />
          <ContactM />
        </div>
        {/* <h1 className="text-3xl font-bold underline">Hello world!</h1> */}
      </main>
    </>
  );
}
